### ISSUE TITLE
Imports 

### ISSUE THREAD

**Issue by michbur** [mckraqs/miniBeamer#15]
::' or ':::' imports not declared from:
    ‘bookdown’ ‘htmltools’ ‘readr’ ‘xfun’
  Unexported objects imported by ':::' calls:
    ‘bookdown:::load_config’ ‘bookdown:::ui_language’
    ‘rmarkdown:::default_mathjax’
    See the note in ?`:::` about the use of this operator.

**Comment by michbur** [comment]
Also: Undefined global functions or variables

**Comment by mckraqs** [comment]
Everything (we hope) declared properly
